name: Release

on:
  push:
    branches-ignore: [dev]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        persist-credentials: false

    - name: Setup Poetry
      uses: snok/install-poetry@v1

    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v3

      id: semantic
      with:
        semantic_version: 18
        extra_plugins: |
          @semantic-release/changelog@6
          @semantic-release/git@10
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_PAT }}
